"""Enum for various lead abilities"""

from enum import IntEnum


class Lead(IntEnum):
    """Enum for various lead abilities"""

    NONE = 255

    SYNCHRONIZE_HARDY = 0
    SYNCHRONIZE_LONELY = 1
    SYNCHRONIZE_BRAVE = 2
    SYNCHRONIZE_ADAMANT = 3
    SYNCHRONIZE_NAUGHTY = 4
    SYNCHRONIZE_BOLD = 5
    SYNCHRONIZE_DOCILE = 6
    SYNCHRONIZE_RELAXED = 7
    SYNCHRONIZE_IMPISH = 8
    SYNCHRONIZE_LAX = 9
    SYNCHRONIZE_TIMID = 10
    SYNCHRONIZE_HASTY = 11
    SYNCHRONIZE_SERIOUS = 12
    SYNCHRONIZE_JOLLY = 13
    SYNCHRONIZE_NAIVE = 14
    SYNCHRONIZE_MODEST = 15
    SYNCHRONIZE_MILD = 16
    SYNCHRONIZE_QUIET = 17
    SYNCHRONIZE_BASHFUL = 18
    SYNCHRONIZE_RASH = 19
    SYNCHRONIZE_CALM = 20
    SYNCHRONIZE_GENTLE = 21
    SYNCHRONIZE_SASSY = 22
    SYNCHRONIZE_CAREFUL = 23
    SYNCHRONIZE_QUIRKY = 24

    CUTE_CHARM_F = 25
    CUTE_CHARM_M = 26

    MAGNET_PULL = 27
    STATIC = 28
    HARVEST = 29
    FLASH_FIRE = 30
    STORM_DRAIN = 31

    PRESSURE = 32
    HUSTLE = PRESSURE
    VITAL_SPIRIT = PRESSURE

    SUCTION_CUPS = 33
    STICKY_HOLD = SUCTION_CUPS

    COMPOUND_EYES = 34
    SUPER_LUCK = COMPOUND_EYES

    ARENA_TRAP = 35
    ILLUMINATE = ARENA_TRAP
    NO_GUARD = ARENA_TRAP
